using System.Net.Http.Json;
using Client.model;
using Microsoft.Extensions.Logging;

namespace Client;

public class ApiClient
{
    private readonly HttpClient _httpClient;
    private readonly ILogger<ApiClient> _logger;

    public ApiClient(HttpClient httpClient, ILogger<ApiClient> logger)
    {
        _httpClient = httpClient;
        _logger = logger;
    }

    /// <summary>
    /// Calls https://localhost:8080/widget/{id}
    /// and logs whether the response came from the fallback.
    /// </summary>
    public async Task<string> GetStatusAsync(int id, CancellationToken cancellationToken = default)
    {
        var relativeUrl = $"widget/{id}";
        _logger.LogInformation("Sending GET {Url}", relativeUrl);

        HttpResponseMessage response = await _httpClient.GetAsync(relativeUrl, cancellationToken);

        if (response.Headers.Contains("X-Fallback"))
        {
            _logger.LogWarning("Response was generated by the Polly fallback strategy.");
        }

        _logger.LogInformation("Received HTTP {StatusCode}", (int)response.StatusCode);

        string body = await response.Content.ReadAsStringAsync(cancellationToken);
        return body;
    }
    
    /// <summary>
    /// Calls https://localhost:8080/widget/{id}
    /// and logs whether the response came from the fallback.
    /// </summary>
    public async Task<Widget> GetWidgetAsync(int id, CancellationToken cancellationToken = default)
    {
        var relativeUrl = $"widget/{id}";
        _logger.LogInformation("Sending GET {Url}", relativeUrl);

        HttpResponseMessage response = await _httpClient.GetAsync(relativeUrl, cancellationToken);

        if (response.Headers.Contains("X-Fallback"))
        {
            _logger.LogWarning("Response was generated by the Polly fallback strategy.");
        }

        _logger.LogInformation("Received HTTP {StatusCode}", (int)response.StatusCode);
        
        var body = await response.Content.ReadFromJsonAsync<Widget>(cancellationToken: cancellationToken);
        return body!;
    }    
}